### ISSUE TITLE
cant get process

### ISSUE THREAD

**Issue by dresiarz222** [vsantiago113/ReadWriteMemory#30]
my code: https://pastebin.com/X99w5k97

i tried using both the get_process_by_name function and get_process_by_id function and they both dont work, heres the output:

`Traceback (most recent call last):
  File "e:\code\readwritememoryPYTHON\memoryTEST.py", line 5, in <module>
    process = ReadWriteMemory().get_process_by_id("16352")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\supre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ReadWriteMemory\__init__.py", line 192, in get_process_by_id
    raise ReadWriteMemoryError(f'Process "{self.process.pid}" not found!')
ReadWriteMemory.ReadWriteMemoryError: Process "-1" not found!`

`Traceback (most recent call last):
  File "e:\code\readwritememoryPYTHON\memoryTEST.py", line 5, in <module>
    process = ReadWriteMemory().get_process_by_name(process_name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\supre\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ReadWriteMemory\__init__.py", line 169, in get_process_by_name
    raise ReadWriteMemoryError(f'Process "{self.process.name}" not found!')
ReadWriteMemory.ReadWriteMemoryError: Process "" not found!`

**Comment by D1RTYS04P** [comment]
Make sure to run the code/IDE as admin. If that doesn't work and you find a solution please let me know I have the same problem 😂😂
